language: node_js
node_js:
  - 8
  - 9
# services:
#   - mongodb
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
# before_script:
#     - |
#       echo "Testing MongoDB connection...";tries=4;
#       i=0;
#       while [ $i -lt $tries ]; do fail=$(mongo --eval db 2>&1 >/dev/null | grep "connect failed");
#         if [ "$fail" ] && [ $[ $i+1 ] -eq $tries ] ; then echo "Error: Could not connect to mongodb"; exit 1;
#         elif [ "$fail" ]; then sleep 3; i=$[ $i+1 ];
#         else echo "OK"; i=$tries; fi;
#       done
install:
  - yarn --ignore-engines
script:
  - yarn ci
